### ISSUE TITLE
[Frontend] :sparkles:  Login Page with magic link and jwt

### ISSUE THREAD

**Issue by ChenBingWei1201** [NTUEE-Web-Programming-Final-Project/final-project#64]
with magic link: https://dashboard.magic.link/app?cid=P8CgB3Mqs45fgsLDYTHi8huAljLgkiNf2m4rbWtLFqQ=
ask required questions
hash a user's password

**Comment by Jackbear8868** [comment]
@jass921026 
![image](https://github.com/NTUEE-Web-Programming-Final-Project/final-project/assets/111693712/f44527d7-135e-4c52-a8c6-157985dc22c5)
